### ISSUE TITLE
external error

### ISSUE THREAD

**Issue by bobbyroylee** [Hampton33/Spooky-Caspar#1]
"external = { path = "../toy-arms/"

It can't find external.  I would imagine it's referring to "https://crates.io/crates/toy-arms/0.9.4" and I tried "toy-arms = {git = "https://github.com/pseuxide/toy-arms", features = ["external"]}" in the .toml file and that gets it further in the compiling process but even then 

"error[E0463]: can't find crate for `external`
 --> src\main.rs:1:1
  |
1 | extern crate external;
  | ^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error[E0463]: can't find crate for `external`
 --> src\sdk\game.rs:1:1
  |
1 | extern crate external;
  | ^^^^^^^^^^^^^^^^^^^^^^ can't find crate"
  
  I can't get this thing to compile for the life of me.  If I download the git page of toy-arms and point it to the external folder via "external = { path = "../toy-arms/external", it gives me over 200 errors.
  
  pls halp

**Comment by fischer36** [comment]
I added the fork to the project directory and updated Cargo.toml to account for it. Download toyarms-fork put it inside your project directory and update Cargo.toml as the path to it is changed.
